os: linux
language: python
python:
  - 3.7

services:
  - docker

install:
  - docker build -t speedtest-exporter .
  - docker run -d -p 0.0.0.0:9102:9102 --name speedtest-exporter speedtest-exporter

before_script:
  - pip install -r requirements-dev.txt

script:
  - docker ps | grep -Fq speedtest-exporter
  - python tests.py
  - docker logs speedtest-exporter 2>&1 | grep -Fc error || true
